# version: '3.4'

services:
  docker_eshop:
    container_name: docker_eshop
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      main-network:
      internal-network: 
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ConnectionStrings__DefaultConnection: "Server=docker_sqlserver; Database=eShop; User Id=sa; Password=StrongPassword2002;TrustServerCertificate=True;"
    depends_on:
      docker_sqlserver:
        condition: service_healthy
  docker_sqlserver:
    container_name: docker_sqlserver
    build:
      context: .
      dockerfile: src/eShop.DAL/db.Dockerfile
    ports:
      - "1433:1433"
    networks:
      internal-network:
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "StrongPassword2002" ,"-Q", "SELECT 1","-C" ]
      interval: 60s
      retries: 20
networks:
  main-network:
    driver: bridge
  internal-network:
    driver: bridge
    internal: true
